# https://blockfuzz.herokuapp.com
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Under Construction
email: juraj.jarmek@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Developing and testing site is at: https://blockfuzz.herokuapp.com
  It will be ported here once developing and testing is finished.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://blockfuzz.com/" # the base hostname & protocol for your site
github_username:  BadProfessor

# Build settings
markdown: kramdown
